server:
  port: 8080
  servlet:
    context-path: /easyStock


spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/easyStock
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

security:
  jwt:
    token:
      secret-key: secretsecretsecretsecretsecretsecretsecretsecret
      expire-length: 36000




